### PR TITLE
docs: tabbify installation section

### PR DESCRIPTION
**Pull request by stefanicjuraj**
Fixes https://github.com/daytonaio/docs/issues/183

### CODE REVIEW

**Comment by stefanicjuraj** [comment]
@ivan-burazin

**Comment by ivan-burazin** [comment]
@Tpuljak are you happy?

**Review by Tpuljak — APPROVED** [review]
Nice work

**Comment by Tpuljak** [comment]
> @Tpuljak are you happy?

Yup 😄

**Comment by Tpuljak** [comment]
@stefanicjuraj lets resolve the conflicts here pls

**Review by ivan-burazin — APPROVED** [review]

**Pull request merged**
