### PR TITLE
Update sidebar icons

### LINKED ISSUE #20: Update navigation items with appropriate icons

### PR DESCRIPTION
**Pull request by osslate**
Fixes #20.

### CODE REVIEW

**Review by Tpuljak — APPROVED** [review]

**Review by ivan-burazin — CHANGES_REQUESTED** [review]
@osslate please use the same icons from https://www.daytona.io/docs/

To be specific:

1. Workspaces Icon is using IDE icon.
2. Server Icon is wrong or missing (there is a whole pallet of icons you can use)
3. Installation we need a logo like this cc @mikimih https://banner2.cleanpng.com/20180329/qgw/kisspng-computer-icons-installation-download-flat-design-soft-5abd33db1f5a87.7486819515223490191284.jpg 
4.

**Comment by mikimih** [comment]
installation

@ivan-burazin  Attached is the icon you requested in SVG format.

Please note that this icon was selected from a different library, but it fits well stylistically with our existing icons. If you know the source from which Nicolas sourced our current icons, please let us know.

**Comment by osslate** [comment]
@ivan-burazin @mikimih I can't find an icon suitable for `Server` in the icons that exist in the repo. The closest I can find it the one I used here (`computer.svg`) but that's also the `Workspaces` icon.

**Comment by nsolerieu** [comment]
@ivan-burazin I used an icon pack as a base set for daytona product: [Mono icons](https://github.com/mono-company/mono-icons)

For more dev tools specific one like like the (`CLI`, `CPU`) I used GitHub open source [Octicons](https://primer.style/foundations/icons)

And in some cases I made some custom ones to fit with the 2 sets above (GPU)

For `install` I recommend using Mono icon `share` as a base and reverse it like this:

Screenshot 2024-05-29 at 9 36 42 AM


[install SVG asset](https://github.com/daytonaio/docs/assets/10632534/abaabefe-b06c-4a91-95c9-14196275b710)

**Comment by ivan-burazin** [comment]
thank you @nsolerieu 🙇 

@osslate are we set now?

**Review by ivan-burazin — APPROVED** [review]

**Pull request merged**
