### PR TITLE
docs: fix broken links & hyperlinks

### PR DESCRIPTION
**Pull request by stefanicjuraj**
This should fix the broken links & hyperlinks in the deployed and local documentation.

### CODE REVIEW

**Comment by Tpuljak** [comment]
@stefanicjuraj would this help? https://docs.astro.build/en/reference/configuration-reference/#base

**Comment by ivan-burazin** [comment]
@Tpuljak lmk what is needed

**Comment by Tpuljak** [comment]
Screenshot 2024-09-06 at 13 08 36

@stefanicjuraj let's address this and we're good to go

**Comment by stefanicjuraj** [comment]
> @stefanicjuraj let's address this and we're good to go

I resolved a conflict unrelated to the error message you are receiving, and do not seem to receive the same log anymore when running the documentation locally - let me know if it still persists for you.

Screenshot 2024-09-06 at 8 20 39 PM

**Review by ivan-burazin — APPROVED** [review]

**Comment by nkkko** [comment]
This needs to be merged as the links are broken, and next week we should expect some traffic. @Tpuljak

**Review by Tpuljak — APPROVED** [review]

**Pull request merged**
