### PR TITLE
docs: add gogs git provider

### PR DESCRIPTION
**Pull request by tarunrajput**
Related: https://github.com/daytonaio/daytona/pull/1255

### CODE REVIEW

**Review by Tpuljak — APPROVED** [review]
Nice work

**Comment by Tpuljak** [comment]
We'll merge this once https://github.com/daytonaio/daytona/pull/1255 is merged.

**Comment by tarunrajput** [comment]
@Tpuljak can we merge this?

**Comment by Tpuljak** [comment]
Thanks for the reminder 😄

**Pull request merged**
