### PR TITLE
47 implement tabbed interface from figma design

### PR DESCRIPTION
**Pull request by Swearengen**

### CODE REVIEW

**Comment by Swearengen** [comment]
I add styles by figma for tabs. We can use starlight tab component in markdown like this:

`import { Tabs, TabItem } from '@astrojs/starlight/components';
...

<Tabs>
  <TabItem label="Stars">
    Sirius, Vega, Betelgeuse
  </TabItem>
  <TabItem label="Moons">
    Io, Europa, Ganymede
  </TabItem>
</Tabs>
`

**Review by osslate — COMMENTED** [review]
Looks mostly correct, but I think there's a difference in bottom padding between the tab title and the underline.

Current state of this PR:
image

Figma:
image

**Comment by Swearengen** [comment]
> Looks mostly correct, but I think there's a difference in bottom padding between the tab title and the underline.
> 
> Current state of this PR: image
> 
> Figma: image
> 
> Edit: the font weight looks different to the design also

@osslate Spacing should be fixed. 
I am not sure why font weight looks different, styling is the same as figma.

**Comment by ivan-burazin** [comment]
> > Looks mostly correct, but I think there's a difference in bottom padding between the tab title and the underline.
> > Current state of this PR: image
> > Figma: image
> > Edit: the font weight looks different to the design also
> 
> @osslate Spacing should be fixed. I am not sure why font weight looks different, styling is the same as figma.

Yes the font looks like its heavier in the pr vs figma

**Comment by Swearengen** [comment]
> > > Looks mostly correct, but I think there's a difference in bottom padding between the tab title and the underline.
> > > Current state of this PR: image
> > > Figma: image
> > > Edit: the font weight looks different to the design also
> > 
> > 
> > @osslate Spacing should be fixed. I am not sure why font weight looks different, styling is the same as figma.
> 
> Yes the font looks like its heavier in the pr vs figma

css Styles are the same as figma. I am not sure that I see the difference when I run docs locally

**Comment by ivan-burazin** [comment]
Where is this implemented so I can test?

**Comment by Swearengen** [comment]
> Where is this implemented so I can test?

You can add 

```
import { Tabs, TabItem } from '@astrojs/starlight/components';

<Tabs>
  <TabItem label="Stars">
    Sirius, Vega, Betelgeuse
  </TabItem>
  <TabItem label="Moons">
    Io, Europa, Ganymede
  </TabItem>
</Tabs>
```

to markdown, and if you have styling I added on this branch you can see how it looks

**Review by ivan-burazin — APPROVED** [review]

**Review by Tpuljak — APPROVED** [review]

**Pull request merged**
