### PR TITLE
docs: add docker remote server requirement

### PR DESCRIPTION
**Pull request by stefanicjuraj**
Fixes https://github.com/daytonaio/docs/issues/129

### CODE REVIEW

**Review by ivan-burazin — CHANGES_REQUESTED** [review]
Would add this to a tip, note or caution flag a to make sure users read it.

Also add a link  to install instructions on dockers website.

Also realised this is missing from the installation and getting started sections. as this is needed for local docker provider (which is default)

**Comment by ivan-burazin** [comment]
@stefanicjuraj 
I think we are missing info for these sections:

    ```
    Remote Port
    >
```
Can i leave it empty? why would I change and to what?

```
    Remote User
    Note: non-root user required
    >
```
Remote User none root? what does this mean what is an example?
```
    Sock Path
    > /var/run/docker.sock
```
What is this, do I change this?

```
    Workspace Data Dir
    The directory on the remote host where the workspace data will be stored
    > /tmp/daytona-data
```
What is this, do I change this?

  ```
  Remote Private Key Path
    daytona_config
    known_hosts
    Custom path
    None
```
Would explain this and the connection to Password, and if you have a pass then none only
cc @Tpuljak & @idagelic as would add also more context in the TUI also

**Comment by stefanicjuraj** [comment]
These were taken directly from the CLI output when running the command. I can provide descriptions for all, but would require assistance from @Tpuljak / @idagelic to know precisely what each input is.

**Comment by Tpuljak** [comment]
> These were taken directly from the CLI output when running the command. I can provide descriptions for all, but would require assistance from @Tpuljak / @idagelic to know precisely what each input is.

`Remote Host`: hostname or IP address of the remote server

`Remote Password`: Password for connecting to the remote server. Can be blank if you are connecting with an SSH key instead

`Remote User`: user that you are authenticating as. Should not be root (and link to the section where we explain why not a root user - should already be somewhere in the docs)

`Sock Path`: Sock path that Docker is listening on on the remote host

`Workspace Data Dir`: Where will the workspace data be stored on the remote server (e.g. cloned repositories)

`Remote Private Key Path`: Path to the remote private key that should be used while authenticating. Can be `None`.

**Comment by ivan-burazin** [comment]
> 
> `Remote User`: user that you are authenticating as. Should not be root (and link to the section where we explain why not a root user - should already be somewhere in the docs)

@Tpuljak can you add an example that can be shown
> 
> `Sock Path`: Sock path that Docker is listening on on the remote host 

I am ok that if there is a pre-filled answer we don't need details

> `Workspace Data Dir`: 

I am ok that if there is a pre-filled answer we don't need details
> 
> `Remote Private Key Path`: Path to the remote private key that should be used while authenticating. Can be `None`.

Set to None if using Password

**Comment by Tpuljak** [comment]
> @Tpuljak can you add an example that can be shown

An example for a user? Not necessary

> Set to None if using Password

Can't. Daytona doesn't even know what's rendering there, the fields are up to the provider but the provider doesn't control the TUI.

**Comment by ivan-burazin** [comment]
```
Remote User: 
Before proceeding, make sure a non-root user on the remote machine exists to allow certain operations.
```


```
Remote Private Key Path: 
Path to the remote private key that should be used while authenticating. Set to None if using password.
```

**Comment by Tpuljak** [comment]
> Set to None if using password.

This is not entirely correct because users can use both methods. if the password fails, it tries the private key.

**Comment by ivan-burazin** [comment]
Agreed. but the other implies that it can be "None", and "no key" that is incorrect.

**Comment by Tpuljak** [comment]
> Agreed. but the other implies that it can be "None", and "no key" that is incorrect.

Not sure what you mean. If the user selects `None`, it doesn't attach a key

**Pull request closed without merging**
