### PR TITLE
Automate CLI reference generation

### LINKED ISSUE #22: Automate CLI reference doc generation
Currently, the CLI reference is edited manually for each release. It appears possible using Cobra (the CLI framework Daytona uses) to [automate Markdown generation](https://cobra.dev/#generating-documentation-for-your-command) based on the commands/subcommands/flags it knows of at runtime.

Implementing this will allow us to generate precise, accurate CLI reference documentation for each release, and ensure that the docs reflect the exact state of Daytona. Once implemented, it means we will not need to manually edit or change the CLI reference docs for accuracy.

cc: @Tpuljak for implementation ideas

### PR DESCRIPTION
**Pull request by osslate**
Closes #22.

This PR adds a CLI reference generation script based on the export from Cobra. The CLI reference for 0.16.x looks like this:

image

## Areas of future improvement
* Include Cobra export fetching logic - can't do a directory listing at download.daytona.io so will need to verify if there's a way to grab it from GitHub / have it zipped with @Tpuljak
  * At the moment, it's expected that the individual `.md` files from the export live in `<REPO>/tmp/cli-docs/`.

### CODE REVIEW

**Comment by Tpuljak** [comment]
OO until Monday but just wanted to mention that the MD files won't live on download.daytona.io. They should only be fetched from Daytona's Github.
If you need directory listing, you can use Github's API.

I can help you out with that on Monday.

**Comment by osslate** [comment]
@Tpuljak sounds good, I'll look into it more in the meantime.

**Review by Tpuljak — COMMENTED** [review]
Code seems okay but is this something that can be done in a deployment pipeline only?

Don't see the value of having this committed to the docs repo.

cc @gdraganic

**Comment by osslate** [comment]
The workflow thought of here is, once a new Daytona release is tagged --- and before the corresponding docs release goes out:

1. I run the script locally to generate docs for the newly tagged Daytona release
2. I verify the contents, commit and push the new autogenerated doc

So this is essentially the last step on my end before a new docs release is tagged and pushed to prod. I'm fine leaving it in `./tools` as it's directly related to the docs publication process, and it also caters for customizing the Markdown before/after the autogenerated stuff (which we'll use later).

There might be a way to automate it in the future, but we don't need to worry about it for now.

**Comment by Tpuljak** [comment]
> There might be a way to automate it in the future, but we don't need to worry about it for now.

Okay, let's leave it for now but I would def recommend we automate this because it seems very "automatable" if that makes sense 😄

**Review by Tpuljak — APPROVED** [review]

**Review by ivan-burazin — CHANGES_REQUESTED** [review]
1. inconsistent "option" markdown, some are code some are bash. not sure which is best @Tpuljak can weigh in
2. Missing overview text
3. Not sure if these are useful; 
daytona
Daytona is a Dev Environment Manager

Synopsis
Daytona is a Dev Environment Manager

**Comment by osslate** [comment]
> 1. inconsistent "option" markdown, some are code some are bash. not sure which is best @Tpuljak can weigh in
> 
>     2. Missing overview text
> 
>     3. Not sure if these are useful;
>        daytona
>        Daytona is a Dev Environment Manager
> 
> 
> Synopsis Daytona is a Dev Environment Manager

1. I can see this now, will fix
2. Will add that back
3. The `daytona` command does _something_, even if the autogenerated docs aren't useful in it's current form. Since these are generated based on docs living in @daytonaio/daytona, I'll also start sending PRs there to make the CLI docs more useful, and gradually, the docs published here will follow.

I'll open an issue over in @daytonaio/daytona to update these docs for now. In the future, updates to the autogenerated CLI reference should probably go over to @daytonaio/daytona as that's where they live, but opening up to @Tpuljak @idagelic for feedback

**Comment by idagelic** [comment]
> I'll open an issue over in @daytonaio/daytona to update these docs for now. In the future, updates to the autogenerated CLI reference should probably go over to @daytonaio/daytona as that's where they live, but opening up to @Tpuljak @idagelic for feedback

That is correct - anything that gets "autogenerated" comes from the main repo and all the descriptions of commands/flags etc. may be changed so if you've got recommendations, just open up an issue.

**Comment by osslate** [comment]
@ivan-burazin fixed the first 2 issues

**Review by ivan-burazin — CHANGES_REQUESTED** [review]
1. daytona - Daytona is a Dev Environment Manager. true daytona is a command as such there should be text ecpain what it does, this is just the title
2. Synopsis Daytona is a Dev Environment Manager. what is Synopsis what does this mean?
3. CLI overview, should be have a bit more fluff. suggest a paragraph for every overview
4. missing core command but has options; daytona container-registry,daytona git-providers...possibly others

**Comment by osslate** [comment]
> 1. daytona - Daytona is a Dev Environment Manager. true daytona is a command as such there should be text ecpain what it does, this is just the title

I agree it needs to be updated. As mentioned in https://github.com/daytonaio/docs/pull/40#issuecomment-2145577937 and https://github.com/daytonaio/docs/pull/40#issuecomment-2145600838, the generated documentation comes directly from Daytona's CLI. In order to update that, we need to submit a PR to the [Daytona repo](https://github.com/daytonaio/daytona/). Whatever you get with `daytona --help` commands is what becomes the docs here.

I'll open a PR to improve the CLI docs, but it won't filter down to the docs site until they're accepted there by Toma/Ivan/Luka and until they become part of a new Daytona release.

> 2. Synopsis Daytona is a Dev Environment Manager. what is Synopsis what does this mean?

I believe the "Synposis" part is generated from one of the "Short" or "Long" descriptions defined here. https://github.com/daytonaio/daytona/blob/main/pkg/cmd/cmd.go#L26-L32

Maybe @Tpuljak or @idagelic have an idea of why this section is generated.

> 3. CLI overview, should be have a bit more fluff. suggest a paragraph for every overview

Is there anything in particular you'd add to the intro? Generally with documentation, the objective is to _avoid fluff_ and focus on getting to the point. I'm not sure what else to add in the intro that's useful for users, but open to suggestions :)

> 4. missing core command but has options; daytona container-registry,daytona git-providers...possibly others

Could you clarify? I can see doc entries for both `daytona container-registry` and `daytona git-providers`:

image

image

**Comment by ivan-burazin** [comment]
> > I believe the "Synposis" part is generated from one of the "Short" or "Long" descriptions defined here. https://github.com/daytonaio/daytona/blob/main/pkg/cmd/cmd.go#L26-L32
> > Maybe @Tpuljak or @idagelic have an idea of why this section is generated.
> 
> That is correct - the synopsis part is generated from the "Long" description. In the CLI it appears when you run a specific command's `--help`. Removing the "long" description also removes the synopsis (as well as the heading). Let me know what you want to have there in an issue on the main repo.

Its fin that the CLI has this, but it makes no sense in the cli, so would just script it to be removed

**Comment by ivan-burazin** [comment]
@osslate needs more context, people don't know anything about Daytona when landing here as such it next to convey what this is as much as possible.

missing commands

**Comment by ivan-burazin** [comment]
@osslate lmk when to review again.

**Review by ivan-burazin — APPROVED** [review]
Approved but @osslate please create issue for table UX bug

**Pull request merged**
